### ISSUE TITLE
write cache failed when use 'h' option

### ISSUE THREAD

**Issue by zhyuri** [portl4t/ts-lua#10]
Hi, thanks for the amazing plugin.

I have some trouble using `ts.cache_write` api to write http object.

```
fd = ts.cache_open(key, TS_LUA_CACHE_WRITE, 'uh')

 n = ts.cache_write(fd, data)
```

the `data` cannot be written into cache.  There are also no error report.
without `h` option, everything is fine.

I'm using ATS 6.2.0 with ts_lua `0.1.7`

**Comment by portl4t** [comment]
如果设置h选项的话，cache_write怕不行，因为http格式数据的存储是分header和body的

**Comment by MatrixYuri** [comment]
唔...看来只能想想办法从底层改造一下InkAPI了，我再想想办法~~
